name: flutter_thmdb_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  google_fonts: ^2.2.0
  intl: 
  build_runner: ^1.11.5
  mobx_codegen: ^2.0.4
  flutter_mobx: ^2.0.2
  mobx: ^2.0.5
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.0
  shared_preferences: ^2.0.12
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true

  assets:
    - .env




